spring.profiles.active: local
---
spring:
  profiles: local
  application:
    name: wsTaxSpring
 # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 159753
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
      allow_update_outside_transaction: false
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        allow_update_outside_transaction: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: test
      javax:
        persistence:
          query:
            timeout: 63000
# Logger configuration
logging:
  path: E:\Work\thai life\logs
  file: ${logging.path}/log-${spring.application.name}.log
# Server configuration
server:
  servlet:
    context-path: /tax
  port: 8080
  
---
spring:
  profiles: dev
  application:
    name: wsTax
 # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dev-cbizdb.thailife.com:5432/corebiz
    username: corebiz.app
    password: C2a7MzO3Mz@jZR
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
      allow_update_outside_transaction: false
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        allow_update_outside_transaction: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: license_exam 
      javax:
        persistence:
          query:
            timeout: 63000
# Server configuration
server:
  servlet:
    context-path: /tax
  port: 8443
logging:
  path: /opt/apache-tomcat-8.5.66/webapps/logsApp/
  file: ${logging.path}/log-${spring.application.name}.log

